# Generated by Django 5.0.2 on 2024-02-08 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_create_phone_number_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.phonenumber'),
        ),
    ]
