# Generated by Django 5.0.2 on 2024-02-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_add_address_and_phone_number_fields_to_custom_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.address')),
                ('phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.phonenumber')),
            ],
        ),
    ]
