# Generated by Django 5.0.2 on 2024-02-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_create_cityzens_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
