# Generated by Django 5.0.2 on 2024-02-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_add_unique_constraint_to_phone_number_number_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'street_number', 'region_name', 'prefecture_name', 'postal_code')},
        ),
    ]
