# Generated by Django 5.0.3 on 2024-04-16 18:53

import django.db.models.deletion
import polls.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_add_unique_constraint_to_address_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_copy', models.FileField(upload_to=polls.models.user_directory_path)),
                ('applicant_photo', models.ImageField(upload_to=polls.models.user_directory_path)),
                ('payment_receipt', models.FileField(upload_to=polls.models.user_directory_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('first_approval', 'First Approval'), ('final_approval', 'Final Approval'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('final_approval_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approvals', to=settings.AUTH_USER_MODEL)),
                ('first_approval_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssuanceMinorsPassportApplication',
            fields=[
                ('passportapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.passportapplication')),
                ('caregiver_address_certification', models.FileField(upload_to=polls.models.user_directory_path)),
                ('convicted_declaration', models.FileField(upload_to=polls.models.user_directory_path)),
                ('minor_age_declaration', models.FileField(upload_to=polls.models.user_directory_path)),
            ],
            bases=('polls.passportapplication',),
        ),
        migrations.CreateModel(
            name='IssuancePassportApplication',
            fields=[
                ('passportapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.passportapplication')),
                ('application_form', models.FileField(upload_to=polls.models.user_directory_path)),
            ],
            bases=('polls.passportapplication',),
        ),
        migrations.CreateModel(
            name='RenewalPassportApplication',
            fields=[
                ('passportapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.passportapplication')),
                ('old_passport_pdf', models.FileField(upload_to=polls.models.user_directory_path)),
            ],
            bases=('polls.passportapplication',),
        ),
        migrations.CreateModel(
            name='ReplacementPassportApplication',
            fields=[
                ('passportapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.passportapplication')),
                ('old_passport_pdf', models.FileField(upload_to=polls.models.user_directory_path)),
            ],
            bases=('polls.passportapplication',),
        ),
        migrations.CreateModel(
            name='TheftOrLossPassportApplication',
            fields=[
                ('passportapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.passportapplication')),
                ('police_report', models.FileField(upload_to=polls.models.user_directory_path)),
            ],
            bases=('polls.passportapplication',),
        ),
    ]
