# Generated by Django 5.0.3 on 2024-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_passportapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('first_approval', 'First Approval'), ('final_approval', 'Final Approval'), ('rejected', 'Rejected'), ('cancelated', 'Cancelated')], default='pending', max_length=20),
        ),
    ]
