# Generated by Django 5.0.3 on 2024-04-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_passportapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportapplication',
            name='departmentx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.department'),
        ),
    ]
