# Generated by Django 5.0.3 on 2024-04-18 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_passportapplication_departmentx'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportapplication',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections', to=settings.AUTH_USER_MODEL),
        ),
    ]
