# Generated by Django 5.0.3 on 2024-04-24 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('passport_number', models.CharField(max_length=100, unique=True)),
                ('date_of_issue', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('issuing_authority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.department')),
                ('passport_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.passportapplication')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
