# Generated by Django 5.0.3 on 2024-04-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_of_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_of_issue',
            field=models.DateField(null=True),
        ),
    ]
