# Generated by Django 5.0.3 on 2024-04-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_passport_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_of_expiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_of_issue',
            field=models.DateField(),
        ),
    ]
