# Generated by Django 5.0.3 on 2024-04-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_passport_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
