# Generated by Django 5.0.3 on 2024-04-24 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_passport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
