# Generated by Django 5.0.3 on 2024-04-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_passport_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='issuing_authority',
        ),
    ]
