# Generated by Django 5.0.3 on 2024-04-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_remove_passport_issuing_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='issuing_authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.department'),
        ),
    ]
