# Generated by Django 5.0.3 on 2024-04-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_passport_issuing_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_of_issue',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
