# Generated by Django 5.0.3 on 2024-04-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_passport_date_of_issue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
    ]
