# Generated by Django 5.0.3 on 2024-04-29 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityzens',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.department'),
        ),
    ]
