# Generated by Django 5.0.3 on 2024-04-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_customuser_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('not_exist', 'Not Exist')], default='active', max_length=20),
        ),
    ]
