# Generated by Django 5.0.3 on 2024-05-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_alter_phonenumber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='email_updated_expiry',
            field=models.BooleanField(default=False),
        ),
    ]
