# Generated by Django 5.0.3 on 2024-05-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_passport_email_updated_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('first_approval', 'First Approval'), ('final_approval', 'Final Approval'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
