# Generated by Django 5.0.3 on 2024-05-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_alter_passportapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportapplication',
            name='application_type',
            field=models.CharField(blank=True, choices=[('Issuance', 'Issuance Passport'), ('Renewal', 'Renewal Passport'), ('Replacement', 'Replacement Passport'), ('TheftOrLoss', 'TheftOrLoss Passport'), ('IssuanceMinors', 'IssuanceMinors Passport')], max_length=30),
        ),
    ]
