# Generated by Django 5.0.3 on 2024-05-30 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_passportapplication_application_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='passport_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.passportapplication'),
        ),
    ]
